# yaml-language-server: https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=greenlight
      - POSTGRES_PASSWORD=greenlight
      - POSTGRES_DB=greenlight
    ports:
      - 5432:5432
    volumes:
      - ./assets/migrations/ddl.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: {}
